FROM nginx:latest
LABEL MAINTAINER DevfullScoopers <devfull@scoopers.com>

# Conf files
COPY nginx/conf.d/odoo-nginx.conf /etc/nginx/conf.d/

# Delete default files
RUN rm /etc/nginx/conf.d/default.conf 

# Expose 8069 port, in which the users will interact with odoo services
EXPOSE 8069